### ISSUE TITLE
Error When Appending Enum to Repeated Field

### ISSUE THREAD

**Issue by BenRKarl** [googleapis/proto-plus-python#201]
This issue appears to be a side effect of the bug fixes released in [1.14.2](https://github.com/googleapis/proto-plus-python/releases/tag/v1.14.0) as it isn't an issue in previous versions.

For context, all the Enums in our API are structured like [this](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v6/enums/access_role.proto#L31), i.e. an outer `message` and inner `enum`.

For a simple repro case, in a `enum_test.py` file paste this:

```py
import proto

class BarEnum(proto.Message):
    class Bar(proto.Enum):
        BAR = 0
        BAZ = 1

class Foo(proto.Message):
    bars = proto.RepeatedField(
        proto.ENUM,
        number=1,
        enum=BarEnum.Bar
    )
```

Then from a repl:

```
>>> from enum_test import Foo, BarEnum
>>> foo = Foo()
>>> bar = BarEnum.Bar.BAR
>>> foo.bars.append(bar)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.pyenv/versions/3.7.0/lib/python3.7/_collections_abc.py", line 971, in append
    self.insert(len(self), value)
  File "~/lib/python3.7/site-packages/proto/marshal/collections/repeated.py", line 178, in insert
    pb_value = self._marshal.to_proto(self._pb_type, value, strict=True)
  File "~/lib/python3.7/site-packages/proto/marshal/marshal.py", line 215, in to_proto
    expected=proto_type.__name__, got=pb_value.__class__.__name__,
TypeError: Parameter must be instance of the same class; expected Bar, got int
```

**Comment by software-dov** [comment]
Able to reproduce, working on a fix.

**Comment by software-dov** [comment]
Turns out the nested enum isn't necessary to reproduce.
