### ISSUE TITLE
Message With Bytes Field Won't Re-Serialize as dict

### ISSUE THREAD

**Issue by kbandes** [googleapis/proto-plus-python#249]
If a message has a bytes field, to_dict serializes the field as a base64 string, which cannot then be read back in to re-create the object.

#### Environment details

  - Programming language: python
  - OS: linux
  - Language runtime version: 3.9.7
  - Package version: 1.19.0

#### Steps to reproduce
```
$ python
Python 3.9.7 (default, Sep  3 2021, 06:18:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import proto
>>> class Blurb(proto.Message):
...   name = proto.Field(proto.STRING, number=1)
...   image = proto.Field(proto.BYTES, number=2)
... 
>>> d1 = {'name': 'ken', 'image': b'abc'}
>>> b1 = Blurb(d1)
>>> b1
name: "ken"
image: "abc"

>>> d2 = Blurb.to_dict(b1)
>>> d2
{'name': 'ken', 'image': 'YWJj'}
>>> b2 = Blurb(d2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/kbandes/.local/lib/python3.9/site-packages/proto/message.py", line 519, in __init__
    super().__setattr__("_pb", self._meta.pb(**params))
TypeError: 'YWJj' has type str, but expected one of: bytes
>>> j1 = Blurb.to_json(b1)
>>> j1
'{\n  "name": "ken",\n  "image": "YWJj"\n}'
>>> b3 = Blurb.from_json(j1)
>>> b3
name: "ken"
image: "abc"
```
Note that to/from json works fine.

**Comment by kbandes** [comment]
Just to belabor that last point, and continue where I left off:
```
>>> import json
>>> b4 = Blurb.from_json(json.dumps(d2))
>>> b4
name: "ken"
image: "abc"
```
To summarize:
Blurb(d2) fails.
Blurb.from_json(json.loads(d2)) succeeds.

**Comment by kbandes** [comment]
Here's the demo in an easy-to-copy version:
```
#!/usr/bin/python

import proto
import traceback


class Blurb(proto.Message):
  name = proto.Field(proto.STRING, number=1)
  image = proto.Field(proto.BYTES, number=2)

d1 = {'name': 'ken', 'image': b'abc'}
print("b1:")
b1 = Blurb(d1)
print(b1)
d2 = Blurb.to_dict(b1)
print("b2:")
try:
  b2 = Blurb(d2)
  print(b2)
except TypeError as e:
  traceback.print_exc()
import json
print("b3:")
b3 = Blurb.from_json(json.dumps(d2))
print(b3)```
