### ISSUE TITLE
Python 3.6 only: 'DatetimeWithNanoseconds.__new__' skipped by base class factory methods

### ISSUE THREAD

**Issue by tseaver** [googleapis/proto-plus-python#256]
At least on Python 3.6:

``bash
$ .nox/unit-3-6/bin/python
Python 3.6.15 (default, Sep 10 2021, 18:02:33) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> from proto.datetime_helpers import DatetimeWithNanoseconds as DWN
>>> DWN.utcnow().replace(tzinfo=datetime.timezone.utc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tseaver/projects/agendaless/Google/src/proto-plus-python/proto/datetime_helpers.py", line 107, in replace
    prev_nanos = self.nanosecond
  File "/home/tseaver/projects/agendaless/Google/src/proto-plus-python/proto/datetime_helpers.py", line 132, in nanosecond
    return self._nanosecond or self.microsecond * 1000
AttributeError: _nanosecond
```

Debugging confirms that `DWN.__new__` is not called by `DWN.utcnow` under Python 3.6.

**Comment by parthea** [comment]
Closing as obsolete as we are dropping support for python 3.6
