### ISSUE TITLE
proto-plus enums fail in conda environments

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/proto-plus-python#469]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: Python
  - OS: Linux
  - Language runtime version: 3.11, 3.12
  - Package version: 1.22, 1.24

#### Steps to reproduce

```
$ conda create -n issue_3129_9 "protobuf<4" google-cloud-aiplatform
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9

  added / updated specs:
    - google-cloud-aiplatform
    - protobuf[version='<4']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    google-api-core-2.11.1     |     pyhd8ed1ab_0          76 KB  conda-forge
    google-api-core-grpc-2.11.1|       hd8ed1ab_0           6 KB  conda-forge
    google-cloud-bigquery-core-3.25.0|     pyhd8ed1ab_0         159 KB  conda-forge
    google-cloud-resource-manager-1.10.4|     pyhd8ed1ab_0          78 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         319 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  abseil-cpp         pkgs/main/linux-64::abseil-cpp-20230802.0-h6a678d5_2 
  aiohttp            pkgs/main/linux-64::aiohttp-3.9.5-py312h5eee18b_0 
  aiosignal          pkgs/main/noarch::aiosignal-1.2.0-pyhd3eb1b0_0 
  annotated-types    pkgs/main/linux-64::annotated-types-0.6.0-py312h06a4308_0 
  attrs              pkgs/main/linux-64::attrs-23.1.0-py312h06a4308_0 
  blas               pkgs/main/linux-64::blas-1.0-openblas 
  brotli-python      pkgs/main/linux-64::brotli-python-1.0.9-py312h6a678d5_8 
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6 
  c-ares             pkgs/main/linux-64::c-ares-1.19.1-h5eee18b_0 
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.3.11-h06a4308_0 
  cachetools         pkgs/main/linux-64::cachetools-5.3.3-py312h06a4308_0 
  certifi            pkgs/main/linux-64::certifi-2024.6.2-py312h06a4308_0 
  cffi               pkgs/main/linux-64::cffi-1.16.0-py312h5eee18b_1 
  charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0 
  cryptography       pkgs/main/linux-64::cryptography-42.0.5-py312hdda0065_1 
  docstring_parser   conda-forge/noarch::docstring_parser-0.16-pyhd8ed1ab_0 
  expat              pkgs/main/linux-64::expat-2.6.2-h6a678d5_0 
  frozenlist         pkgs/main/linux-64::frozenlist-1.4.0-py312h5eee18b_0 
  geos               pkgs/main/linux-64::geos-3.8.0-he6710b0_0 
  google-api-core    conda-forge/noarch::google-api-core-2.11.1-pyhd8ed1ab_0 
  google-api-core-g~ conda-forge/noarch::google-api-core-grpc-2.11.1-hd8ed1ab_0 
  google-auth        pkgs/main/linux-64::google-auth-2.29.0-py312h06a4308_0 
  google-cloud-aipl~ conda-forge/noarch::google-cloud-aiplatform-1.58.0-pyhd8ed1ab_0 
  google-cloud-bigq~ conda-forge/noarch::google-cloud-bigquery-core-3.25.0-pyhd8ed1ab_0 
  google-cloud-core  pkgs/main/linux-64::google-cloud-core-2.3.2-py312h06a4308_0 
  google-cloud-reso~ conda-forge/noarch::google-cloud-resource-manager-1.10.4-pyhd8ed1ab_0 
  google-cloud-stor~ pkgs/main/linux-64::google-cloud-storage-2.6.0-py312h06a4308_0 
  google-crc32c      pkgs/main/linux-64::google-crc32c-1.5.0-py312h5eee18b_0 
  google-resumable-~ pkgs/main/linux-64::google-resumable-media-2.4.0-py312h06a4308_0 
  googleapis-common~ pkgs/main/linux-64::googleapis-common-protos-1.56.4-py312h06a4308_0 
  googleapis-common~ pkgs/main/linux-64::googleapis-common-protos-grpc-1.56.4-py312h06a4308_0 
  grpc-cpp           pkgs/main/linux-64::grpc-cpp-1.48.2-he1ff14a_4 
  grpc-google-iam-v1 conda-forge/noarch::grpc-google-iam-v1-0.13.1-pyhd8ed1ab_0 
  grpcio             pkgs/main/linux-64::grpcio-1.48.2-py312he1ff14a_4 
  grpcio-status      pkgs/main/noarch::grpcio-status-1.41.1-pyhd3eb1b0_0 
  gtest              pkgs/main/linux-64::gtest-1.14.0-hdb19cb5_1 
  idna               pkgs/main/linux-64::idna-3.7-py312h06a4308_0 
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1 
  libcrc32c          pkgs/main/linux-64::libcrc32c-1.1.2-h6a678d5_0 
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1 
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1 
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-11.2.0-h00389a5_1 
  libgfortran5       pkgs/main/linux-64::libgfortran5-11.2.0-h1234567_1 
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1 
  libopenblas        pkgs/main/linux-64::libopenblas-0.3.21-h043d6bf_0 
  libprotobuf        pkgs/main/linux-64::libprotobuf-3.20.3-he621ea3_0 
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1 
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0 
  multidict          pkgs/main/linux-64::multidict-6.0.4-py312h5eee18b_0 
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0 
  numpy              pkgs/main/linux-64::numpy-1.26.4-py312h2809609_0 
  numpy-base         pkgs/main/linux-64::numpy-base-1.26.4-py312he1a6c75_0 
  openssl            pkgs/main/linux-64::openssl-3.0.14-h5eee18b_0 
  packaging          pkgs/main/linux-64::packaging-24.1-py312h06a4308_0 
  pip                pkgs/main/linux-64::pip-24.0-py312h06a4308_0 
  proto-plus         pkgs/main/linux-64::proto-plus-1.22.1-py312h06a4308_0 
  protobuf           pkgs/main/linux-64::protobuf-3.20.3-py312h6a678d5_0 
  pyasn1             pkgs/main/noarch::pyasn1-0.4.8-pyhd3eb1b0_0 
  pyasn1-modules     pkgs/main/noarch::pyasn1-modules-0.2.8-py_0 
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0 
  pydantic           pkgs/main/linux-64::pydantic-2.5.3-py312h06a4308_0 
  pydantic-core      pkgs/main/linux-64::pydantic-core-2.14.6-py312hb02cf49_0 
  pyopenssl          pkgs/main/linux-64::pyopenssl-24.0.0-py312h06a4308_0 
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py312h06a4308_0 
  python             pkgs/main/linux-64::python-3.12.4-h5148396_1 
  python-dateutil    pkgs/main/linux-64::python-dateutil-2.9.0post0-py312h06a4308_2 
  re2                pkgs/main/linux-64::re2-2022.04.01-h295c915_0 
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0 
  requests           pkgs/main/linux-64::requests-2.32.2-py312h06a4308_0 
  rsa                pkgs/main/noarch::rsa-4.7.2-pyhd3eb1b0_1 
  setuptools         pkgs/main/linux-64::setuptools-69.5.1-py312h06a4308_0 
  shapely            pkgs/main/linux-64::shapely-2.0.1-py312h1789038_1 
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1 
  sqlite             pkgs/main/linux-64::sqlite-3.45.3-h5eee18b_0 
  tk                 pkgs/main/linux-64::tk-8.6.14-h39e8969_0 
  typing-extensions  pkgs/main/linux-64::typing-extensions-4.11.0-py312h06a4308_0 
  typing_extensions  pkgs/main/linux-64::typing_extensions-4.11.0-py312h06a4308_0 
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0 
  urllib3            pkgs/main/linux-64::urllib3-2.2.2-py312h06a4308_0 
  wheel              pkgs/main/linux-64::wheel-0.43.0-py312h06a4308_0 
  xz                 pkgs/main/linux-64::xz-5.4.6-h5eee18b_1 
  yarl               pkgs/main/linux-64::yarl-1.9.3-py312h5eee18b_0 
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_1 


Proceed ([y]/n)? y


Downloading and Extracting Packages:
                                                                                                                                                                                       
Preparing transaction: done                                                                                                                                                            
Verifying transaction: done                                                                                                                                                            
Executing transaction: done                                                                                                                                                            
#
# To activate this environment, use
#
#     $ conda activate issue_3129_9
#
# To deactivate an active environment, use
#
#     $ conda deactivate

avolkov@avolkov:~$ conda activate issue_3129_9
(issue_3129_9) avolkov@avolkov:~$ python -c 'import google.cloud.aiplatform_v1beta1.services.dataset_service'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/__init__.py", line 21, in <module>
    from .services.dataset_service import DatasetServiceClient
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/__init__.py", line 16, in <module>
    from .client import DatasetServiceClient
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/client.py", line 53, in <module>
    from google.cloud.aiplatform_v1beta1.services.dataset_service import pagers
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/pagers.py", line 27, in <module>
    from google.cloud.aiplatform_v1beta1.types import annotation
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/types/__init__.py", line 365, in <module>
    from .feature_online_store_service import (
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/types/feature_online_store_service.py", line 112, in <module>
    class FetchFeatureValuesRequest(proto.Message):
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/types/feature_online_store_service.py", line 143, in FetchFeatureValuesRequest
    class Format(proto.Enum):
  File "/usr/local/google/home/avolkov/anaconda3/envs/issue_3129_9/lib/python3.12/site-packages/proto/enums.py", line 61, in __new__
    idx = attrs._member_names.index(pb_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'index'

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
This appears to be a known issue. The error occurs with proto-plus-1.22.1 when using Python 3.11. The stack trace looks similar to the one in https://github.com/googleapis/proto-plus-python/issues/326. The issue was fixed in https://github.com/googleapis/proto-plus-python/pull/329 and available in [v1.22.2](https://github.com/googleapis/proto-plus-python/releases/tag/v1.22.2). 


I will open a PR to bump the minimum version of `proto-plus` in `google-cloud-aiplatform` to 1.22.3 similar to https://github.com/googleapis/gapic-generator-python/blob/6fc3d22b697ed14ef2daa18bbd0964026caed850/gapic/templates/setup.py.j2#L37

https://github.com/googleapis/python-aiplatform/blob/80fa75c50bd65e6ead39568ee8ceb12f70733fa6/setup.py#L249

I'm going to close this issue as no code changes are needed in this repository.
