### ISSUE TITLE
Couldn't build proto file into descriptor pool [Python 3.13]

### ISSUE THREAD

**Issue by cdce8p** [googleapis/proto-plus-python#490]
Encountered this issue while testing `Python 3.13.0rc2`. To reproduce

```py
import proto

__protobuf__ = proto.module(
    package="some_module",
    manifest={"View", "Encoding"},
)

class View(proto.Enum):
    A = 0

class Encoding(proto.Enum):
    B = 0
```

```py
$ python test.py
Traceback (most recent call last):
  File "/.../proto-plus-python/test.py", line 11, in <module>
    class Encoding(proto.Enum):
        B = 0
  File "/.../proto-plus-python/proto/enums.py", line 105, in __new__
    file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../proto-plus-python/proto/_file_info.py", line 104, in generate_file_pb
    pool.Add(self.descriptor)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'some_module.__firstlineno__'
```

```
$ pip list
Package    Version
---------- -------
pip        24.2
proto-plus 1.24.0
protobuf   5.28.2
```

--
AFAICT the issue shows up as soon as two `proto.Enum` are defined in one module. A quick experiment suggests that the reason might be here
https://github.com/googleapis/proto-plus-python/blob/e5e85339ffce7660253a60065927cf791a4ed2b7/proto/enums.py#L72-L78
The attributes are only filtered by `if isinstance(number, int)`. Python 3.13 added the new `__firstlineno__` attribute which is an integer and as such not filtered as it should be. Just changing the condition here would be enough to resolve it, just not sure that's the best option as I'm unfamiliar with the code base.
```diff
-if isinstance(number, int)
+if isinstance(number, int) and name != "__firstlineno__"
```

**Comment by cdce8p** [comment]
Some of the affected packages. There might be more
- `google-cloud-texttospeech==2.17.2`
```py
import google.cloud.texttospeech
```
- `google-cloud-speech==2.27.0`
```py
import google.cloud.speech_v1
```
- `google-generativeai==0.8.3`
```py
import google.generativeai
```
- `google-cloud-pubsub==2.26.0`
```py
import google.cloud.pubsub_v1
```
